### ISSUE TITLE
Startup Script Failed

### ISSUE THREAD

**Issue by s-crypt** [ArchiveTeam/Ubuntu-Warrior#8]
Downloading a fresh image on Windows 10 with VirtualBox gives this error.
![image](https://user-images.githubusercontent.com/41712656/93013824-be80d080-f560-11ea-9d94-a55a86c2d46c.png)

**Comment by chfoo** [comment]
Is it still having that error? Can you try logging into the warrior? 

1. Use Alt+left and Alt+right to switch to a login console.
2. Login with `root` and `archiveteam`
3. Run `docker ps -a` and post screenshot
4. Run `docker logs 9208`
5. Use Shift+PageUp and Shift+PageDown to scroll the console. See if there's any error and post screenshot of it.

**Comment by s-crypt** [comment]
I am now getting a new error
I cannot run the docker commands, as it gives the first error `(unix:///var/run/docker.sock)`
I tried restarting the docker service but that did not work.

![image](https://user-images.githubusercontent.com/41712656/93119440-ab602480-f676-11ea-856c-a9003a227b2b.png)

---

**Edit**
After disabling a TAP device on the windows host, I am able to run the commands.
![image](https://user-images.githubusercontent.com/41712656/93120166-d008cc00-f677-11ea-9604-ca7706bff793.png)

**Comment by chfoo** [comment]
Someone suggested editing `/etc/conf.d/docker` to have `DOCKER_OPTS="--debug"`, restarting the docker service, and checking the docker log file `/var/log/docker.log`. I am still checking what can cause the start up to fail.

**Comment by s-crypt** [comment]
![image](https://user-images.githubusercontent.com/41712656/93284664-02095380-f788-11ea-8b4a-c097a042a7a1.png)
![image](https://user-images.githubusercontent.com/41712656/93284747-27965d00-f788-11ea-816b-ea524249985c.png)
 Here is the log file. I hope this is helpful 🙃

**Comment by cyberbalsa** [comment]
I noticed you are running Hyper-V Hypervisor. (The turtle in the bottom) I
would make sure networking is working.

**Comment by s-crypt** [comment]
Yes, I had an issue with networking before, but once I disabled a TAP device that I had running the it was able to download the docker file correctly. I will try disabling hypervisor and report if anything changed.

**Edit:** Nope. Disabled hyper-v completely, restarted, and gives the same error.
![image](https://user-images.githubusercontent.com/41712656/93424739-7833b600-f86d-11ea-8c68-439ce952d533.png)

**Comment by chfoo** [comment]
Any luck so far? Are you importing a new appliance each time? Some ideas for troubleshooting, if you haven't tried yet, is to keep the default settings, then import a new appliance each time with settings you want to change.

**Comment by s-crypt** [comment]
I have tried and still no luck. I had it working a few years ago, and the actual image hasn't been updated since it was working. 
The only change I can think of is something with virtualbox.

Side note: is an update planned for the image? (updated dependencies, os, kernel, etc)

**Comment by chfoo** [comment]
I made a new version of the appliance using the latest Alpine release. I'm not sure if it will fix the problem however. The appliance has been uploaded to the Releases section and to the regular download URL https://warriorhq.archiveteam.org/downloads/warrior3/

**Comment by s-crypt** [comment]
**Somehow that worked!** 
I tested the old and new with the same settings, and the appliance download and installed properly, and failed on the old one.

There is just one very minor new problem: I cannot access the web interface using the address provided, by either the localhost, 127.0.0.1, or by navigating to the local IP address, as I am using bridged mode.

**EDIT:** I restarted the appliance with NAT networking and it looks like it is functional!

**Comment by chfoo** [comment]
That's good news! About bridge mode, there's been issues in the past with network conflict problems. I'm not familiar with networking and Docker administration so I don't have any idea why bridge mode wouldn't work.

**Comment by s-crypt** [comment]
The only small bug I run into is that I have to manually (automatic retries don't work) restart the startup with ctrl+c 5 times or less, as one process fails or an appliance does not start correctly. But once it is up and running, it works normally.

BTW, Thank you so much for your help!
